controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Twig and assets packages are needed to use swagger ui.
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
