nelmio_api_doc:
    documentation:
        info:
            title: Notes App
            description: This is a note-taking app that allows you to create and delete notes, even organise them in folders.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
